# Generated by Django 3.1.2 on 2020-10-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='location',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.IntegerField(choices=[(0, 'Processing'), (1, 'Upload'), (2, 'Transcribe'), (3, 'Translate'), (4, 'Subtitle'), (5, 'Completed')], default=0),
        ),
    ]
