# Generated by Django 3.1.2 on 2020-10-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20201025_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lenguage',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
